from termcolor import colored
from time import sleep


def greeting():
    """Generated by figlet"""
    print(r"       ___          _        _   ")
    print(r"      | _ \_ _ ___ (_)___ __| |_ ")
    print(r"      |  _/ '_/ _ \| / -_) _|  _|")
    print(r"      |_| |_| \___// \___\__|\__|")
    print(r"  ___ _    _    _ |__/       _  _ ")
    print(r" / __| |_ (_)__| |_____ _ _ | || |__ _ _ __  ")
    print(r"| (__| ' \| / _| / / -_) ' \| __ / _` | '  \ ")
    print(r" \___|_||_|_\__|_\_\___|_||_|_||_\__,_|_|_|_|")
    print("")


def notify_until(function, message, color="red", interval=5):
    condition = function()
    while not condition:
        condition = function()
        if not condition:
            print("\b" * len(message) +
              colored(message, color),
              end="",
              flush=True)
            sleep(interval)
